<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/2_1_3_Arr_Or_Pr_2_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science va Sun'iy Intellekt Praktikum

#Ma'lumotlar Tahlili

#2.1 Numpy kutubxonasi bilan ishlash

#Numpy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.3 Massivga yo'naltirilgan dasturlash

Arifmetik amallar

#Ko'paytirish, bo'lish, qo'shish, ayirish va h.k amallar

In [7]:
# data
arr1 = np.arange(6).reshape(2, 3) # 0~6 bo'lgan elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3) # 6~12 bo'lgan elementlardan tashkil topgan array

In [8]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
# Ko'paytirish
arr1 * arr2 # arr1 ning elementlarini arr2 ning mos elementlariga ko'paytirish

array([[ 0,  7, 16],
       [27, 40, 55]])

In [10]:
# bo'lish
arr2/arr1 # arr2 ning elementlarini arr1 ning mos elementlariga bo'lish

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [11]:
# qo'shish
arr1 + arr2 # arr1 ning elementlarini arr2 ning mos elementlariga qo'shish

array([[ 6,  8, 10],
       [12, 14, 16]])

In [12]:
# ayirish
arr2 - arr1 # arr2 ning elementlaridan arr1 ning mos elementlarini ayirish

array([[6, 6, 6],
       [6, 6, 6]])

In [15]:
# kvadratga oshirish (square)
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [16]:
# kvadrat ildiz (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])