<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/2_1_2_Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science va Sun'iyh Intellekt Praktikum

#Ma'lumotlar Tahlili

#2.1 Numpy kutubxonasi bilan ishlash

Numpy kutubxonasini chaqirib olish

In [2]:
import numpy as np

2.1.2 Universal Funksiyalar

Unary funksiyalar (bitta argument qabul qilivchi funksiya)

# `sqrt`, `square`, `exp`, `log`, `modf`, `sign`, `isnan` funksiyalarini ko'rib chiqamiz

In [4]:
arr = np.arange(10) # 0 ~ 10 gacha bo'lgan elementlardan iborat massivni qaytaradi
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# `sqrt` massivning har bir elementini kvadrat ildizini qaytaradi

In [5]:
np.sqrt(arr) # arr nomli massivning barcha elementlarining kvadrat ildizini qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

# `sqr` massivning har bir elementini kvadratga oshiradi

In [10]:
np.square(arr) # arr nomli massivning barcha elementlarini kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

# `exp` massivning har bir elementini exponentini qaytaradi

In [11]:
np.exp(arr) # arr nomli massivning har bir elementini exponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

# `log` massivning har bir elementining logarifmini hisoblaydi (loge)

In [15]:
np.log(arr[1:]) # arr nomli massivning 0 elementdan tashqari barcha elementining logarifmini hisoblaydi (loge)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

# `modf` haqiqiy sonlarni butun va qoldiq qismga ajratib beradi

In [20]:
arr1 = np.random.randn(6) # 6 ta elementdan iborat tahminiy qiymatlarga ega massiv
arr1

array([ 0.57470357,  0.85623198, -0.83582186,  0.05833983,  0.27742513,
       -1.02681077])

In [21]:
qoldiq, butun = np.modf(arr1) # arr1 elementlarini qoldiq va butun qismlarini ikkita massivga ajratadi

In [22]:
print(qoldiq)
print(butun)

[ 0.57470357  0.85623198 -0.83582186  0.05833983  0.27742513 -0.02681077]
[ 0.  0. -0.  0.  0. -1.]


# `sign` massiv elementlarning qiymati manfiy bo'lsa `-1` va aksincha musbat bo'lsa `1` qaytaradi

In [24]:
np.sign(arr1) # arr1 massivining ishoralarini -1 va 1 ko'rinishda qaytaradi

array([ 1.,  1., -1.,  1.,  1., -1.])

# `isnan` massiv elementlarida `NaN` ma'lumot bo'lsa `True` qaytaradi va aksincha esa `False` qaytaradi

In [25]:
arr1

array([ 0.57470357,  0.85623198, -0.83582186,  0.05833983,  0.27742513,
       -1.02681077])

In [26]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [29]:
arr1[0] = np.NaN # 0 - elementni NaNga lamashtirish
arr1

array([        nan,  0.85623198, -0.83582186,  0.05833983,  0.27742513,
       -1.02681077])

In [30]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

#Binary funksiyalar (ikkita argument qabul qiluvchi funksiyalar)

# `add`, `multiply`, `maximum` funksiyalarini ko'rib chiqamiz

In [31]:
# 2 ta massiv yaratib olamiz
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [32]:
arr2

array([-1.1316853 , -0.86298627, -1.11006831,  0.41695951,  0.2058973 ,
        1.13986026])

In [33]:
arr3

array([-0.42010249,  0.25483471,  2.45896294, -0.14052548, -2.67575322,
       -0.65978612])

# `add` funksiyasi massivlar elementlarini mos ravishda qo'shish

In [34]:
np.add(arr2, arr3) # arr2 va arr3 massivlar elementlarini mos ravishda qo'shish

array([-1.5517878 , -0.60815156,  1.34889463,  0.27643403, -2.46985592,
        0.48007414])

In [36]:
arr2 + arr3 # arr2 va arr3 massivlar elementlarini mos ravishda qo'shish

array([-1.5517878 , -0.60815156,  1.34889463,  0.27643403, -2.46985592,
        0.48007414])

# `multiply` ikkita massivning mos elemementlarini ko'paytirish

In [37]:
arr2

array([-1.1316853 , -0.86298627, -1.11006831,  0.41695951,  0.2058973 ,
        1.13986026])

In [38]:
arr3

array([-0.42010249,  0.25483471,  2.45896294, -0.14052548, -2.67575322,
       -0.65978612])

In [40]:
np.multiply(arr2, arr3) # arr2 va arr3 ning mos elemementlarini ko'paytirish

array([ 0.47542382, -0.21991886, -2.72961682, -0.05859344, -0.55093037,
       -0.75206398])

# `maximum` ikkita massivning elementlarini taqqoslab kattasining elementini qaytaradi

In [41]:
np.maximum(arr2, arr3) # arr2 va arr3 massivlarning elementlarini taqqoslab kattasining elementini qaytaradi

array([-0.42010249,  0.25483471,  2.45896294,  0.41695951,  0.2058973 ,
        1.13986026])