<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/2_1_3Arr_Or_Pr_1_Math%26Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science va Sun'iy Intellekt Praktikum

#Ma'lumotlar Tahlili

#2.1 Numpy kutubxonasi bilan ishlash

Numpy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.3 Massivga yo'naltirilgan dasturlash

#Matematik va Statik usullarni qo'llash

In [4]:
# data
arr = np.random.randn(5, 4)  # (5, 4) o'lchamli massiv (random)
arr

array([[ 2.80836507, -1.45609451,  1.95199932, -0.69468148],
       [ 1.3617752 ,  2.18171949,  1.13531885, -0.27548828],
       [ 1.93264983,  0.84752822,  1.6572865 , -0.46136856],
       [-2.12078327, -0.47376791, -1.07686154, -0.19918121],
       [-1.16281792,  0.12494724, -1.10125037, -2.1378748 ]])

#`sum` methodi (yig'indi)

In [5]:
arr.sum() # arr ning bacha elementlari yig'indisini hisoblab beradi

2.8414198662064885

In [6]:
np.sum(arr) # arr ning bacha elementlari yig'indisini hisoblab beradi

2.8414198662064885

In [7]:
arr.sum(axis = 1) # qator yig'indi

array([ 2.6095884 ,  4.40332526,  3.97609599, -3.87059393, -4.27699586])

In [8]:
arr.sum(axis = 0) # ustun yig'indi

array([ 2.81918891,  1.22433253,  2.56649275, -3.76859432])

#`mean` methodi (o'rtacha arifmetik qiymat)

In [9]:
# sodda ma'lumot
data = np.arange(5) # 0~5 bo'lgan elementlardan tashkil topgan massiv
data

array([0, 1, 2, 3, 4])

In [11]:
mean = np.sum(data)/len(data)
mean

2.0

In [12]:
# numpy mean
np.mean(data)

2.0

In [14]:
data.mean()

2.0

In [15]:
arr

array([[ 2.80836507, -1.45609451,  1.95199932, -0.69468148],
       [ 1.3617752 ,  2.18171949,  1.13531885, -0.27548828],
       [ 1.93264983,  0.84752822,  1.6572865 , -0.46136856],
       [-2.12078327, -0.47376791, -1.07686154, -0.19918121],
       [-1.16281792,  0.12494724, -1.10125037, -2.1378748 ]])

In [16]:
np.mean(arr) # arr ning o'rtacha qiymati

0.1420709933103244

In [17]:
np.mean(arr, axis = 1) # qator bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.6523971 ,  1.10083132,  0.994024  , -0.96764848, -1.06924896])

In [18]:
np.mean(arr, axis = 0) # ustun bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.56383778,  0.24486651,  0.51329855, -0.75371886])

In [19]:
arr.mean(axis = 1) # qator bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.6523971 ,  1.10083132,  0.994024  , -0.96764848, -1.06924896])

In [20]:
arr.mean(axis = 0) # ustun bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.56383778,  0.24486651,  0.51329855, -0.75371886])

#`cumsum` methodi (cumilitive sum - yig'ib boriladigan yig'indi)

In [21]:
data

array([0, 1, 2, 3, 4])

In [22]:
data.cumsum()

array([ 0,  1,  3,  6, 10])

In [23]:
np.cumsum(data)

array([ 0,  1,  3,  6, 10])

In [24]:
 arr.cumsum(axis = 0) # ustun bo'yicha cumsum

array([[ 2.80836507, -1.45609451,  1.95199932, -0.69468148],
       [ 4.17014027,  0.72562498,  3.08731817, -0.97016976],
       [ 6.1027901 ,  1.57315321,  4.74460466, -1.43153832],
       [ 3.98200683,  1.0993853 ,  3.66774312, -1.63071952],
       [ 2.81918891,  1.22433253,  2.56649275, -3.76859432]])

In [25]:
arr.cumsum(axis = 1) # qator bo'yicha cumsum

array([[ 2.80836507,  1.35227056,  3.30426988,  2.6095884 ],
       [ 1.3617752 ,  3.54349469,  4.67881354,  4.40332526],
       [ 1.93264983,  2.78017805,  4.43746455,  3.97609599],
       [-2.12078327, -2.59455118, -3.67141272, -3.87059393],
       [-1.16281792, -1.03787068, -2.13912106, -4.27699586]])

In [26]:
np.cumsum(arr, axis = 0) # ustun bo'yicha cumsum

array([[ 2.80836507, -1.45609451,  1.95199932, -0.69468148],
       [ 4.17014027,  0.72562498,  3.08731817, -0.97016976],
       [ 6.1027901 ,  1.57315321,  4.74460466, -1.43153832],
       [ 3.98200683,  1.0993853 ,  3.66774312, -1.63071952],
       [ 2.81918891,  1.22433253,  2.56649275, -3.76859432]])

In [27]:
np.cumsum(arr, axis = 1) # qator bo'yicha cumsum

array([[ 2.80836507,  1.35227056,  3.30426988,  2.6095884 ],
       [ 1.3617752 ,  3.54349469,  4.67881354,  4.40332526],
       [ 1.93264983,  2.78017805,  4.43746455,  3.97609599],
       [-2.12078327, -2.59455118, -3.67141272, -3.87059393],
       [-1.16281792, -1.03787068, -2.13912106, -4.27699586]])