<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/2_1_3Arr_Or_Pr_1_Logical_Set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science va Sun'iy Intellekt Praktikum

#Ma'lumotlar Tahlili

#2.1 Numpy kutubxonasi bilan ishlash

Numpy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.3 Massivga yo'naltirilgan dasturlash

Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

Shart operatori sifatida `where` dan foydalanish

Tasavvur qiling bizda ikkita ma'lumotlar (massivlar) to'plami mavjud bular: `xarr` va `yarr`. Agar shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [2]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [3]:
# Shart
cond = np.array([True, False, True, True, False])

In [4]:
# where
result = np.where(cond, xarr, yarr) # cont == True : xarr elementi, cond == False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr = np.random.randn(4, 4) # (4, 4) tahminiy massiv
arr

array([[ 1.33799872,  0.46626033,  1.77932983, -0.81846101],
       [ 0.21951172,  0.27894767, -0.29208565,  1.01105846],
       [-0.17839134, -0.27511146, -0.05850491, -0.09775747],
       [-0.80548178, -0.70872238, -0.10422076,  0.18424564]])

In [6]:
# where
results = np.where(arr < 0, -2, 2) # arr ning manfiy elemnentlarini -2 ga, musbat elementlarini esa 2 ga almashtirish
results

array([[ 2,  2,  2, -2],
       [ 2,  2, -2,  2],
       [-2, -2, -2, -2],
       [-2, -2, -2,  2]])