<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/2_1_3_Arr_Or_Pr_4Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science va Sun'iy Intellekt

№Ma'luimotlar Tahlili

#2.1 Numpy kutubxonasi bilan ishlash

#Numpy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.3 Massivga yo'nal;tirilgan dasturlash

#Tartiblash (`Sorting`)

In [2]:
# data
arr = np.random.rand(4) # 4 ta tahminiy elementlardan tashkil topgan massiv
arr

array([0.79253461, 0.02546188, 0.82653479, 0.27703287])

#`sort` funksiyasi

In [3]:
# 1 usul
sorted_arr = np.sort(arr) # arr massivimizning tartiblangan nusxasi
sorted_arr

array([0.02546188, 0.27703287, 0.79253461, 0.82653479])

In [4]:
# 2 usul
arr.sort() # arr ning tartiblangan ko'rinishi
arr

array([0.02546188, 0.27703287, 0.79253461, 0.82653479])

In [5]:
# teskari tartiblash
rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.82653479, 0.79253461, 0.27703287, 0.02546188])

In [6]:
# 2D array
arr2d = np.random.randn(2, 4) # (2, 4) random array
arr2d

array([[-0.64457122, -0.59643937,  1.52086093, -0.10797423],
       [-0.35192348, -0.74863215,  0.26421455, -2.14518994]])

In [7]:
arr2d.shape

(2, 4)

In [8]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, 0) # arr2d ning har bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[-0.64457122, -0.74863215,  0.26421455, -2.14518994],
       [-0.35192348, -0.59643937,  1.52086093, -0.10797423]])

In [10]:
# axis = 1 --> ustun
col_str = np.sort(arr2d, 1) # arr2d ning har bir ustun bo'yicha tartiblangan ko'rinishi
col_str

array([[-0.64457122, -0.59643937, -0.10797423,  1.52086093],
       [-2.14518994, -0.74863215, -0.35192348,  0.26421455]])