<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/_1_Creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum

#Ma'lumotlar Tahlili

2.1 NumPy kutubxonasi bilan ishlash

NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.1 N -o'lchamli massiv (array)larga ishlov berish

NumPy da massiv yaratishning eng oson yo'llaridan biri bu array funksiyasi yordamida amalga oshiriladi.  Va ushbu funksiya har qanday turdagi ketma-ket ma'lumotlarni qabul qilib, uni yangi NumPy arrayiga o'girib beradi.

In [9]:
data1 = [3.5, 5, 6, 2] # list
arr1 = np.array(data1)

In [10]:
arr1

array([3.5, 5. , 6. , 2. ])

In [11]:
data2 = (4, 5, 3.2, 7) # tuple
arr2 = np.array(data2)

In [7]:
arr2

array([4. , 5. , 3.2, 7. ])

#Massiv o'lchami

In [12]:
arr1.ndim # arr1 ning o'lchami

1

In [14]:
arr2.ndim # arr2 ning o'lchami

1

#Ikki va undan katta o'lchamli massivlar

In [15]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # list ichidagi list (nested list)
arr3 = np.array(data3) # array3

In [17]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr3.ndim #array3 ning o'lchami

2

#Uch o'lchamli massiv

In [25]:
data4 = [[[1, 2], [3, 4], [5, 6], [7, 8]], [[9, 10], [11, 12], [13, 14], [15, 16]], [[17, 18], [19, 20], [21, 22], [23, 24]]]
arr4 = np.array(data4)

In [26]:
data4

[[[1, 2], [3, 4], [5, 6], [7, 8]],
 [[9, 10], [11, 12], [13, 14], [15, 16]],
 [[17, 18], [19, 20], [21, 22], [23, 24]]]

In [27]:
arr4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [28]:
arr4.ndim

3

#shape, size metodlari
shape - massivning qator va ustunlariz
size - massivdagi elementlar soni

In [29]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
arr3.shape # qator va ustunlar (q, u)

(2, 4)

In [33]:
arr3.size # elementlar soni

8

N - o'lchamli massivlar yaratishning boshqa usullari

zeros va ones funksiyalari yordamida massivlar yaratish

In [45]:
arr4 = np.zeros(shape = (2, 4)) # barcha elementlari 0 ga teng bo'lgan (2, 4)
arr4
arr4 = np.zeros(shape = (2, 4)) # barcha elementlari 0 ga teng bo'lgan (2, 4)
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
arr5 = np.ones(shape = (2, 4)) # barcha elementlari 1 ga teng bo'lgan (2, 4)
arr5
arr5= np.ones((2, 4)) # barcha elementlari 1 ga teng bo'lgan (2, 4)
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arange funksiyasi yordamida yaratish

In [47]:
arr6 = np.arange(4, 20, 2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
arr7 = np.arange(20) # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])