<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/_2_data_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#MA'LUMOT TURLARI

Massiv yaratishda ma'lumot turlarini aniq kiritish, ma'lumot turlarini aniqlash, bir ma'lumot turidan ikkinchi turdagi ma'lumot turiga o'girish.

In [2]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [3]:
arr2 = np.array([1, 2, 3], dtype = np.int32)
arr2

array([1, 2, 3], dtype=int32)

**dtype** methodi

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr2.dtype

dtype('int32')

Bir turdagi ma'lumot turidan boshqasiga o'girish

In [6]:
arr = np.array([1, 2, 3, 4]) #int64
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int64')

**astype** methodi

In [9]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [11]:
data = np.array([3.4, 5.7, 1.8, 4]) #float64
data.dtype

dtype('float64')

In [14]:
int_data = data.astype(np.int64)
int_data.dtype

dtype('int64')