<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/_4_Boolean_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science va Sun'iy Intellect Praktkum

#Ma'lumotlar Tahlili

#2.1 Numpy kutubxonasi bilan ishalsh

Numpy kutubxonasini chaqirib olish

In [1]:
 import numpy as np

2.1.1 N - o'lchamli massiv(array)larga ishlov berish

Boolean Indexlash

In [2]:
# Ismlar
names = np.array(["Hasan", "Husan", "Mirzabek", "Elyor", "Hasan", "Javohir", "Elyor"])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [3]:
# data
data = np.random.randn(7, 4)
data

array([[-1.24907778, -1.05207174,  2.48324286, -0.55452807],
       [ 0.39325313,  0.10813685,  0.14416371,  1.81688655],
       [ 0.61746751,  0.10738532,  1.65211741, -0.66339715],
       [-0.85809802,  1.26637803, -1.27498661,  1.32318824],
       [ 1.6416371 ,  0.12096526,  1.91215914, -1.00940434],
       [-1.19800364,  0.15524778, -0.13187991,  0.20694928],
       [ 1.93494448,  1.13824216,  0.53842837,  0.50104291]])

In [4]:
names == "Hasan"

array([ True, False, False, False,  True, False, False])

In [5]:
data[names == "Hasan"] # Hasanga tegishli barcha ma'lumotlarni ajratib olish

array([[-1.24907778, -1.05207174,  2.48324286, -0.55452807],
       [ 1.6416371 ,  0.12096526,  1.91215914, -1.00940434]])

In [6]:
data[names == "Elyor"] # Elyorga tegishli barcha ma'lumotlarni ajratib olish

array([[-0.85809802,  1.26637803, -1.27498661,  1.32318824],
       [ 1.93494448,  1.13824216,  0.53842837,  0.50104291]])

In [7]:
data[names == "Mirzabek"]

array([[ 0.61746751,  0.10738532,  1.65211741, -0.66339715]])

In [9]:
data[names == "Hasan", 2:] # Hasanga tegishli oxirgi 2 ta ustundagi ma'lumotlarni ajratib olish

array([[ 2.48324286, -0.55452807],
       [ 1.91215914, -1.00940434]])

In [11]:
data[names == "Husan", :2]

array([[0.39325313, 0.10813685]])

In [13]:
data[names != "Hasan"] # (!=)Hasandan tashqari barcha insonlarning ma'lumotlarini ajratib olish

array([[ 0.39325313,  0.10813685,  0.14416371,  1.81688655],
       [ 0.61746751,  0.10738532,  1.65211741, -0.66339715],
       [-0.85809802,  1.26637803, -1.27498661,  1.32318824],
       [-1.19800364,  0.15524778, -0.13187991,  0.20694928],
       [ 1.93494448,  1.13824216,  0.53842837,  0.50104291]])

In [16]:
data[~(names == "Hasan")] # (~)Hasandan tashqari barcha insonlarning ma'lumotlarini ajratib olish. Yuqoridagi cell bilan bir xil natija

array([[ 0.39325313,  0.10813685,  0.14416371,  1.81688655],
       [ 0.61746751,  0.10738532,  1.65211741, -0.66339715],
       [-0.85809802,  1.26637803, -1.27498661,  1.32318824],
       [-1.19800364,  0.15524778, -0.13187991,  0.20694928],
       [ 1.93494448,  1.13824216,  0.53842837,  0.50104291]])

In [19]:
data[(names == "Hasan")|(names == "Husan")] # Hasan va Husanlargaa tegishli ma'lumnotlarni ajratib olish

array([[-1.24907778, -1.05207174,  2.48324286, -0.55452807],
       [ 0.39325313,  0.10813685,  0.14416371,  1.81688655],
       [ 1.6416371 ,  0.12096526,  1.91215914, -1.00940434]])

In [21]:
mask = (names == "Hasan")|(names == "Husan") # "|"" or  (yoki)
mask

array([ True,  True, False, False,  True, False, False])

In [23]:
data[mask] # Hasan va Husanlargaa tegishli ma'lumnotlarni ajratib olish

array([[-1.24907778, -1.05207174,  2.48324286, -0.55452807],
       [ 0.39325313,  0.10813685,  0.14416371,  1.81688655],
       [ 1.6416371 ,  0.12096526,  1.91215914, -1.00940434]])

In [24]:
data

array([[-1.24907778, -1.05207174,  2.48324286, -0.55452807],
       [ 0.39325313,  0.10813685,  0.14416371,  1.81688655],
       [ 0.61746751,  0.10738532,  1.65211741, -0.66339715],
       [-0.85809802,  1.26637803, -1.27498661,  1.32318824],
       [ 1.6416371 ,  0.12096526,  1.91215914, -1.00940434],
       [-1.19800364,  0.15524778, -0.13187991,  0.20694928],
       [ 1.93494448,  1.13824216,  0.53842837,  0.50104291]])

In [27]:
data[data < 0] = 0 # data massivining 0 dan kichik barcha elementlarini 0 ga aylantirish
data

array([[0.        , 0.        , 2.48324286, 0.        ],
       [0.39325313, 0.10813685, 0.14416371, 1.81688655],
       [0.61746751, 0.10738532, 1.65211741, 0.        ],
       [0.        , 1.26637803, 0.        , 1.32318824],
       [1.6416371 , 0.12096526, 1.91215914, 0.        ],
       [0.        , 0.15524778, 0.        , 0.20694928],
       [1.93494448, 1.13824216, 0.53842837, 0.50104291]])