<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/_5_Transposing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science va Sun'iy Intellekt Praktikum

#Ma'lumotlar Tahlili

#2.1 Numpy kutubxonasi bilan ishlash

Numpy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.1. N - o'lchamli massiv (array)larga ishlov berish

# Massivlar pozitsiyasini ko'chirish **`Transpose`** va o'qlar o'rnin almashtirish **`Swapping axes`**

# **`reshape`** metodi

In [4]:
A = np.arange(6).reshape(3, 2) # A massiv : Elementlari 0~6, shape (3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
A.T # A massivning Transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

# **`swapping axes`**

In [6]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.swapaxes(1, 0) # A massivning Transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

# **`Transpose`**ning ishlatiolishiga bir misol AA*T*

In [9]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
np.dot(A, A.T) # AA^T dan hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])