<a href="https://colab.research.google.com/github/omullaboyev/data-science/blob/main/WorkingWithFiles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science va Sun'iy Intellekt Praktirum

#Ma'lumotlar Tahlili. Numpy kutubxonasi.

Fayllar bilan ishlash

In [2]:
import numpy as np

In [6]:
# data
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#`save` funksiyasi - bitta arrayni bitta faylga saqlash

In [5]:
# save
np.save("data", arr) # arr massivni data.npy fayliga saqlaydi

#`load` (yuklash, o'qish) metodi

In [8]:
# load
load_arr = np.load("data.npy") # data.npy faylni load_arr massiviga yuklab (o'qib) oladi
load_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# data
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#`savez` funksiyasi - bir nechta arrayni bitta faylga saqlash

In [11]:
np.savez("arrays", a = arr, b = arr1) # arr va arr1 massivlarini arrays.npz fayliga saqlaydi

#.npz fayldan massivlarni yuklab (o'qib) olish

In [12]:
arrays = np.load("arrays.npz") # arrays.npz fayldagi a va b massivlarni arrays massiviga yuklaydi

#.npz fayldan o'qilgan (yuklangan) massivlarga murojaat

In [13]:
arrays["a"] # savez funksiyasida ko'rsatilgan kalit so'z (a) orqali o'qiladi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arrays["b"] # savez funksiyasida ko'rsatilgan kalit so'z (b) orqali o'qiladi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#`savez_compressed` funksiyasi - bir nechta arrayni bitta faylga arxivlab saqlaydi

In [15]:
np.savez_compressed("arrays_copmressed", a = arr, b = arr1) # arr va arr1 massivlarini arrays_compressed.npz fayliga saqlaydi

#compressed .npz fayldan massivlarni yuklab (o'qib) olish

In [17]:
arrays_comp = np.load("arrays_copmressed.npz") # arrays_compressed.npz fayldagi a va b massivlarni arrays_comp massiviga yuklaydi

#compressed npz fayldan o'qilgan (yuklangan) massivlarga murojaat

In [18]:
arrays_comp["a"] # savez_compressed funksiyasida ko'rsatilgan kalit so'z (a) orqali o'qiladi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arrays_comp["b"] # savez_compressed funksiyasida ko'rsatilgan kalit so'z (b) orqali o'qiladi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])